### ISSUE TITLE
Mark as Deprecated ?

### ISSUE THREAD

**Issue by Carreau** [Siecje/xontrib-prompt-ret-code#2]
Hey, 

It seem that your package has been merged into Xonsh core, though Google seem to reference it high, 
would you mind marking it as deprectated if this is the case. 

Thanks

**Comment by Siecje** [comment]
How should I do that?

**Comment by Carreau** [comment]
> How should I do that?

I would just add a big warning at the top of the readme. Some project even make the master-branch have only the readme.

At startup you can also look at `xonsh.__version__` and print a warning that this is now in xonsh core.

if you want to be aggressive you can `sys.exit()` in `setup.py`.

I'll add on my todo list to send a PR if that can be of help.
